### ISSUE TITLE
Rehydrated reason for use

### ISSUE THREAD

**Issue by alexanderchan** [aws-amplify/docs#281]
**Is your feature request related to a problem? Please describe.**
Was looking for a reason that Rehydrated is needed

**Describe the solution you'd like**
https://tylermcginnis.com/building-serverless-react-graphql-apps-with-aws-appsync/

> Rehydrated will wait until the application cache has been read and is ready to use in the app before rendering the app. By default, this just shows some loading text, but this can be configured with our own UI like this if we would like:

https://hackernoon.com/aws-appsync-up-and-running-560a42d96ba7
> Rehydrated is a helper from the aws-appsync-react library that will basically wait to render the application until the data is fetched from the API and the application is wired up with the AWSAppSyncClient

**Describe alternatives you've considered**
See links above

**Additional context**
Please include some text and an example of why and how to use.

**Comment by nikhil-dabhade** [comment]
@alexanderchan Thank you for the feedback. 
What documentation link were you following when you ran in to rehydrate? 
Can you confirm if this is the one https://aws-amplify.github.io/docs/cli/graphql?sdk=js#tutorial-s3--react ?

**Comment by nikhil-dabhade** [comment]
@alexanderchan : Sorry to bug you again. Can you confirm is the above was the only page where you ran in to Rehydrate ?

**Comment by alexanderchan** [comment]
Hello, @nikhil-dabhade yes that's the only place I ran into Rehydrate.  Thanks!

**Comment by nikhil-dabhade** [comment]
@alexanderchan Thank you for confirming. I will circle back on the date to update this by next week.

**Comment by idanlo** [comment]
Any updates?

**Comment by idanlo** [comment]
not stale

**Comment by idanlo** [comment]
not stale

**Comment by cyrfer** [comment]
I also do not understand why it is recommended. I removed it because it added a `<div>` and messed up my flexbox layout. I'm hopeful removing it won't mess up my client Subscriptions.

Mention of `<Rehydrated>` component is here:
https://github.com/awslabs/aws-mobile-appsync-sdk-js

**Comment by nagad814** [comment]
@nikhil-dabhade any update on this. As this currently breaking a production app.

**Comment by mauerbac** [comment]
In looking at the AppSync SDK issue, it seems to be merged. This issue should be resolved. Please  open a new issue for further assistance.

**Comment by aagamdoshi** [comment]
This issue isn't yet resolved, Kindly confirm, I faced the same issue
